allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - esbuild
  - sharp
updateConfig:
  ignoreDependencies:
    - orval
