#!/usr/bin/env bash
# One-shot dev setup: write docker/.env (once) with every value the stack uses, then bring it up.
# This is a dev project with nothing secret to protect (the frontend is a public OIDC client and the
# backend is a resource server — neither needs a secret), so the values are fixed, working dev
# credentials. The host-run backend/frontend use the same defaults, so nothing needs exporting.
set -euo pipefail
cd "$(dirname "$0")"

ENV_FILE=".env"
if [[ -f "${ENV_FILE}" ]]; then
  echo "docker/.env already exists — keeping it (delete it to regenerate)."
else
  echo "Generating docker/.env ..."
  cat > "${ENV_FILE}" <<'EOF'
# Generated by docker/init.sh — local dev stack. Safe to delete and regenerate.

# App database (Keycloak gets its own `keycloak` DB in the same instance).
POSTGRES_USER=codillas
POSTGRES_PASSWORD=codillas
POSTGRES_DB=codillas

# Keycloak master-admin console — http://localhost:8080 (admin / admin).
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin

# minio (S3 for the files module) — console http://localhost:9001.
MINIO_ROOT_USER=codillas
MINIO_ROOT_PASSWORD=codillas123
MINIO_BUCKET=codillas
EOF
  echo "Wrote docker/.env"
fi

docker compose -f docker-compose.dev.yml --profile full up -d --build

cat <<'EOF'

Stack is starting:
  Postgres   localhost:5432            (codillas / codillas)  + a `keycloak` DB
  Keycloak   http://localhost:8080     console admin/admin · realm: codillas
  minio      http://localhost:9001     (codillas / codillas123)  bucket: codillas
  mailpit    http://localhost:8025

App logins (realm users):  admin/admin · teacher/teacher · student/student

Then: (cd backend && mvn spring-boot:run)  and  (cd frontend && pnpm dev)
EOF
